# trigger:
#   branches:
#     include:
#       - '*'

pool:
  name: linux-agent-pool

# stages:
#   - stage: Build
#     jobs:
#       - job: BuildJob
#         steps:
#           # Using an if-else template expression to execute different steps
#           - ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
#               - script: echo "This is the main branch."
#           - ${{ else }}:
#               - script: echo "This is not the main branch."


trigger:
  branches:
    include:
      - '*'

parameters:
  - name: targetBranch
    type: string
    default: $[ variables['Build.SourceBranchName'] ]

variables:
  # Define the message variable conditionally
  - ${{ if eq(parameters.targetBranch, 'main') }}:
      - name: message
        value: 'Deploying to Production'
  - ${{ if ne(parameters.targetBranch, 'main') }}:
      - name: message
        value: 'Deploying to Non-Production'

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        steps:
          - script: echo "Branch is $(Build.SourceBranchName)"
          - script: echo "Message $(message)"



