trigger:
  branches:
    include:
      - '*'
pool:
  name: linux-agent-pool

variables:
  ${{ if or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release')) }}:
    branchName: 'master'
  ${{ else }}:
    branchName: 'develop'

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        steps:
          - script: echo "Target Environment is $(branchName)"




