trigger:
  branches:
    include:
      - '*'
pool:
  name: linux-agent-pool

# variables:
#   # Define the branchName variable conditionally
#   - ${{ if or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release')) }}:
#       - name: branchName
#         value: 'master'
#   - ${{ if and(ne(variables['Build.SourceBranch'], 'refs/heads/master'), not(startsWith(variables['Build.SourceBranch'], 'refs/heads/release'))) }}:
#       - name: branchName
#         value: 'develop'

variables:
  ${{ if or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release')) }}:
    branchName: 'master'
  ${{ else }}:
    branchName: 'develop'

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        steps:
          - script: echo "Target Environment is $(branchName)"




