trigger:
  branches:
    include:
      - '*'

parameters:
  - name: os
    type: string
    default: 'linux'
    values:
      - win
      - linux
      - mac

variables:
  ${{ if eq(parameters.os, 'win') }}:
    testsFolder: 'windows'
  ${{ elseif eq(parameters.os, 'linux') }}:
    testsFolder: 'linux'
  ${{ else }}:
    testsFolder: 'mac'

stages:
- stage: Test
  jobs:
  - job: EchoVariable
    steps:
      - script: echo "Value of testsFolder: $(testsFolder)"
        displayName: "Display Conditional Variable"
