pool:
  name: linux-agent-pool

name: Deploy Bicep files

variables:
  serviceConnectionName: 'eng-lab-automation'
  location: 'uksouth'
  templateFile: '$(Build.Repository.LocalPath)/Bicep/main.bicep'
  parameterFile: '$(Build.Repository.LocalPath)/Bicep/env/dev.bicepparam'

stages:  
  - stage: Lint
    jobs:
      - job: LintCode
        displayName: Lint code
        steps:
          # Validate Bicep parameter file is valid bicepparam
          - task: CmdLine@2
            name: Validate_Bicep_Parameters_File
            displayName: Validate Bicep Parameters File
            inputs:
              script: az bicep build-params --file ${{ variables.parameterFile }} --stdout

          # Format Bicep file 
          - task: CmdLine@2
            name: Format_Bicep
            displayName: Format Bicep
            inputs:
              script: |
                az bicep format --file ${{ variables.templateFile }}
              failOnStderr: true  

          # Validate Bicep file 
          - task: CmdLine@2
            name: Validate_Bicep
            displayName: Validate Bicep
            inputs:
              script: |
                az bicep build --file ${{ variables.templateFile }} --stdout
              failOnStderr: true 

  - stage: ValidatePreviewDeployment
    dependsOn: Lint
    jobs:
      - job: ValidatePreviewDeployment
        displayName: Validate & Preview Deployment
        steps:
          # Validate Bicep Deployment
          - task: AzureCLI@2
            name: Bicep_Deployment_Validation
            displayName: Bicep Deployment Validation
            inputs:
              azureSubscription: ${{ variables.serviceConnectionName }}
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az deployment sub validate --location uksouth \
                --template-file ${{ variables.templateFile }} \
                --parameters ${{ variables.parameterFile }}
              workingDirectory: $(Pipeline.Workspace)

          # Preview Bicep Deployment
          - task: ARMDeploymentInsights@2
            name: Preview_Bicep_Template
            displayName: Preview Bicep Deployment
            inputs:
              deploymentName: ${{ variables.DeploymentName }}
              deploymentScope: 'Subscription'
              armServiceConnection: ${{ variables.serviceConnectionName }}
              subscriptionId: ${{ variables.subscriptionId }}
              location: 'UK South'
              templateLocation: 'File'
              templateFile: '${{ variables.templateFile }}'
              templateParametersFile: '${{ variables.parameterFile }}'

  - stage: Deploy
    dependsOn: ValidatePreviewDeployment
    jobs:
      - deployment: Deploy
        environment: DEV
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                # Deploy Bicep Deployment
                - task: AzureCLI@2
                  name: Infrastructure_Deployment
                  displayName: Infrastructure Deployment
                  inputs:
                    azureSubscription: ${{ variables.serviceConnectionName }}
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      az deployment sub create --location uksouth \
                      --template-file ${{ variables.templateFile }} \
                      --parameters ${{ variables.parameterFile }}
                    workingDirectory: $(Pipeline.Workspace)
