pool:
  vmImage: ubuntu-latest

name: Deploy Bicep files

variables:
  serviceConnectionName: 'eng-lab-automation'
  location: 'uksouth'
  templateFile: '$(Build.Repository.LocalPath)/Bicep/main.bicep'
  parameterFile: '$(Build.Repository.LocalPath)/Bicep/env/dev.bicepparam'
  DeploymentName: main
  subscriptionId: 800eeb5c-ab87-468f-800b-d9ca632b4f73

stages:  
  - stage: Lint
    jobs:
      - job: LintCode
        displayName: Lint code
        steps:               
          - task: MicrosoftSecurityDevOps@1
            displayName: 'Microsoft Security DevOps'
            inputs:
              categories: 'IaC'
              config: '$(Build.Repository.LocalPath)/Bicep/checkov-linux.gdnconfig'
              publish: true
              artifactName: 'CodeAnalysisLogs'